### PR TITLE
feat: add algolia search

### LINKED ISSUE #50: Use Algolia DocSearch
We've already applied to the DocSearch program. Now we're waiting for their reply. Many thanks to @kahnwong. Once they reply with a good news, we can enable this cool feature. 😊

See [Using Algolia DocSearch](https://docusaurus.io/docs/search#using-algolia-docsearch) for more detail.

### PR DESCRIPTION
**Pull request by kahnwong**
- Revert "Merge pull request #48 from chonla/feature/search"
- add algolia search

### CODE REVIEW

**Comment by kahnwong** [comment]
preview

image

**Comment by kahnwong** [comment]
@zkan could you DM me your email so I can invite you to algolia project for hosting search indexes?

**Comment by zkan** [comment]
It looks awesome!

PS. @kahnwong I dm you on Discord.

**Comment by kahnwong** [comment]
merge loey mai 🤣

**Comment by zkan** [comment]
จัดให้ อิอิ

**Pull request merged**
